### ISSUE TITLE
L'authentification avec Persona ne marche pas

### ISSUE THREAD

**Issue by Flaburgan** [apprentimag/Apprentidate#1]
Après avoir validé mon adresse mail quand la fenêtre se ferme, une popup apparaît rapidement puis disparait sans que j'ai le temps de la lire. Je ne semble pas connecté après (le bouton en bas de la page est toujours sign in).

Ubuntu 12.04 - Firefox 16.0 beta

**Comment by marienfressinaud** [comment]
Je t'avoue que je ne sais pas... J'ai essayé avec Firefox et Chromium et ça marche bien. Tu vois donc la popup qui te demande ton adresse, tu valides et après y en une deuxième qui s'ouvre mais disparaît juste après ?

**Comment by Flaburgan** [comment]
yep, la pop qui s'ouvre est celle que tu as en utilisant alert(), pas une vraie fenêtre. La console Firebug n'affiche rien de plus que le GET https://login.persona.org/wsapi/session_context 200 OK 293ms à la fin, mais elle affiche "login" "logout" pendant la connexion.

**Comment by Flaburgan** [comment]
Voici le contenu complet de la console de Firefox : 

## [19:35:24,721] L'API de la console de journalisation (console.log, console.info, console.warn, console.error) a été désactivée par un script sur cette page.

[19:36:07,230] POST http://apprentimag.fr/apprentidate/login [HTTP/1.1 200 OK 1364ms]
[19:36:07,232] GET https://login.persona.org/wsapi/session_context [HTTP/1.1 200 OK 293ms]
[19:36:07,637] POST http://apprentimag.fr/apprentidate/logout [HTTP/1.1 200 OK 829ms]
[19:36:08,535] GET http://apprentimag.fr/apprentidate/# [HTTP/1.1 200 OK 168ms]
[19:36:08,615] NS_ERROR_NOT_AVAILABLE: prompt aborted by user @ resource:///components/nsPrompter.js:425
[19:36:08,718] GET http://apprentimag.fr/apprentidate/theme/base.css#/ [HTTP/1.1 304 Not Modified 24ms]
[19:36:08,720] GET https://login.persona.org/include.js [HTTP/1.1 304 Not Modified 357ms]
[19:36:08,723] GET http://apprentimag.fr/apprentidate/scripts/jquery.js#/ [HTTP/1.1 304 Not Modified 48ms]
[19:36:08,691] Erreur d'analyse de la valeur pour « background ».  Déclaration abandonnée. @ http://apprentimag.fr/apprentidate/theme/base.css#/:95
[19:36:08,691] Couleur attendue, mais « top » trouvé.  Erreur d'analyse de la valeur pour « background ».  Déclaration abandonnée. @ http://apprentimag.fr/apprentidate/theme/base.css#/:97
[19:36:08,692] Propriété « -moz-border-radius » inconnue.  Déclaration abandonnée. @ http://apprentimag.fr/apprentidate/theme/base.css#/:316
[19:36:08,693] Propriété « -moz-box-shadow » inconnue.  Déclaration abandonnée. @ http://apprentimag.fr/apprentidate/theme/base.css#/:322
[19:36:09,203] GET http://apprentimag.fr/apprentidate/theme/img/dinner.jpg [HTTP/1.1 304 Not Modified 32ms]
[19:36:09,207] GET https://login.persona.org/communication_iframe [HTTP/1.1 304 Not Modified 386ms]
[19:36:09,708] GET https://login.persona.org/wsapi/session_context [HTTP/1.1 200 OK 185ms]

**Comment by marienfressinaud** [comment]
Bizarre, ça devrait être suivi par un : GET https://login.persona.org/wsapi/list_emails
Tu peux me donner la réponse de la ligne session_context ?

**Comment by Flaburgan** [comment]
URL de la requête:  https://login.persona.org/wsapi/session_context
Méthode de la requête:    GET
Code d'état: HTTP/1.1 200 OK

En-têtes de la requête 19:44:26,000  

X-Requested-With:XMLHttpRequest
User-Agent:Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:16.0) Gecko/20100101 Firefox/16.0
Referer:https://login.persona.org/communication_iframe
Host:login.persona.org
DNT:1
Content-Type:application/x-www-form-urlencodedConnection:keep-alive
Accept-Language:fr,fr-fr;q=0.8,en-us;q=0.5,en;q=0.3
Accept-Encoding:gzip, deflate
Accept:application/json;text/plain

En-têtes de la réponse Δ186ms

X-Frame-Options:DENYStrict-Transport-Security:max-age=2592000; includeSubdomainsSet-Cookie:browserid_state=w4LDi1HDmgTCn0oVH8O9wpXDjzLDvMOiJQ.wqvCmsOhf8KrGsOiw4rCuwJ-wpcza8OIwqHCmcOiw403wpnCt8O6OCtgRcOCwokzGi18OFV5w5LCgg5vSsOSMDs7wo8Rcw.1349631866930.2419200000.Hn9OwpFQXmRMa8Orw7hpwp9jfsO1bsKuw6UYdsKKwp_Ct8OPwq0fwpvDqijDusOO; path=/wsapi; expires=Sun, 04 Nov 2012 17:44:26 GMT; secure; httponlyDate:Sun, 07 Oct 2012 17:44:26 GMTContent-Type:application/json; charset=utf-8Content-Length:214Connection:keep-aliveCache-Control:no-cache, max-age=0

**Comment by marienfressinaud** [comment]
Nan ce que je veux c'est la réponse du serveur, pas les en-têtes, ça devrait être du json en principe. Mais je sais pas si on peut l'avoir avec la console de Firefox, en tout cas on peut avec Firebug

**Comment by Flaburgan** [comment]
La réponse est la page HTML classique, je vois rien de particulier là dedans..

**Comment by marienfressinaud** [comment]
Nop, https://login.persona.org/wsapi/session_context doit retourner un truc du genre

```
{"csrf_token":"un_token","server_time":1349640933698,"authenticated":true,"auth_level":"password","domain_key_creation_time":1323891030781,"random_seed":"un_truc_random","data_sample_rate":0,"userid":1318817}
```

(j'ai modifié des trucs parce que j'ai aucune idée si y a des trucs sensibles dedans :p (même si j'en doute))

C'est visible grâce à Firebug en déroulant le menu GET  https://login.persona.org/wsapi/session_context, onglet "Réponse". C'est pas une page html à proprement parlé...

Mais bon, faudrait mieux que tu me montres en direct histoire que je vois ;)

**Comment by Flaburgan** [comment]
Oui oui mais je l'ai bien cette réponse, sauf que j'ai authenticated:false.

{"csrf_token":"bjvS7BKBK40WWoAJCGxYLw==","server_time":1349641361847,"authenticated":false,"domain_key_creation_time":1323898170781,"random_seed":"sBnvpSW5MXMUfeQrA51/LsW6BVnFsisTVVI2g2s0LZw=","data_sample_rate":0}

Donc tu gères pas le refus, et on sait pas non plus pourquoi je suis refusé :P

**Comment by marienfressinaud** [comment]
Bin voilà c'est ce que je voulais savoir :p bon je verrai demain pour gérer au niveau du refus et t'afficher un joli message... Mais si ça t'amuse, ça se passe ici : https://github.com/marienfressinaud/Apprentidate/blob/master/app/controllers/indexController.php ligne 33 :)

**Comment by Flaburgan** [comment]
Ouais je fais 36 trucs en même temps alors j'ai pas regardé les infos importantes j'ai collé sans faire gaffe.

Du coup je peux fixer ça demain aprem, mets moi les droits pour push.

**Comment by marienfressinaud** [comment]
Normalement un popup s'ouvre dans le cas d'un échec et devrait t'indiquer le problème. En même temps y a un truc très bizarre avec Persona : il y a deux cas de base "success" et "failure". Sauf que quand tu es dans le cas d'un success, tu as encore deux possibilité : le résultat peut être soit "okay" soit "failure". C'est un coup à se prendre la tête ><

**Comment by Flaburgan** [comment]
J'ai jeté un coup d'oeil à ton code, et je confirme que je suis bien dans error: j'ai la popup Login failure qui s'affiche est disparait juste après avec marqué "login failure : [object Object]" (ou quelque chose dans le genre, pas le temps de lire.). Je mets une trace dans la console pour voir.

$.ajax({
   type: 'POST',
   url: login_url,
   data: {assertion: assertion},
   success: function(res, status, xhr) {
   (...)
   },
   error: function(res, status, xhr) {
   console.error("onlogin : login failure : res = " + res + " status = " + status + " xhr = " + xhr);
   alert("login failure : " + res);
  }
 });

J'ai push, si tu veux mettre à jour le code sur ton serveur.

**Comment by marienfressinaud** [comment]
Ça marche toujours pas ? :trollface:

**Comment by Flaburgan** [comment]
Persona est maintenant un projet mort.

**Comment by marienfressinaud** [comment]
Tout comme Apprentidate :p

**Comment by carrieje** [comment]
Essayé après un update du système relationnel des ERP en version 6 bêta.
Toujours non fonctionnel. Même après désactivation du module Bluetooth sous Mac OS Big Sur.

**Comment by carrieje** [comment]
> Tout comme Apprentidate :p

Par contre ça c'est faux. Le site est toujours accessible :trollface:

**Comment by marienfressinaud** [comment]
![Capture d’écran de 2020-12-02 11-23-45](https://user-images.githubusercontent.com/1436309/100860500-dfd2c800-3490-11eb-91f5-79a860387a28.png)

T'as eu chaud toi !

**Comment by Flaburgan** [comment]
P'tain mais c'est vrai en plus.

Dat project. Mobilizon 10 ans plus tôt.

**Comment by marienfressinaud** [comment]
Et voilà, apprentimag.fr et Apprentidate sont partis. Une page de l'histoire des apprentis de l'Ensimag se tourne. Soyons forts !
