### ISSUE TITLE
Problème d'encodage dans le nom d'utilisateur

### ISSUE THREAD

**Issue by guillaumededrie** [apprentimag/Apprentidate#16]
Les caractères accentués dans les noms d'utilisateurs apparaissent avec un problème d'encodage.

![expl_pb_encodage](https://f.cloud.github.com/assets/636498/679897/43bb81ce-d97f-11e2-82e9-13999fea86f3.jpg)

**Comment by hamadr** [comment]
Je n'arrive pas à le reproduire chez moi, une erreur de configuration côté apache ?
![proofbug](https://f.cloud.github.com/assets/1525665/2178187/2fbbe4de-965d-11e3-8f45-457ae0f02f04.png)

**Comment by guillaumededrie** [comment]
... je crois que ça a été résolu en même temps qu'un autre commit depuis le temps (8 mois !), tu peux la fermer (l'issue :-) )

**Comment by Flaburgan** [comment]
:p

**Comment by marienfressinaud** [comment]
Tu peux rouvrir je crois : http://apprentimag.fr/apprentidate/?c=event&a=see&id=7

Sinon une bonne pratique ce serait de s'assurer que toutes les chaînes qu'on manipule sont encodées en UTF-8. C'est super lourd à gérer, mais c'est comme ça qu'on fait pour FreshRSS et ça fait un moment qu'on n'a pas eu de soucis (même des sites en arabe ou indien passent très bien :D)

**Comment by marienfressinaud** [comment]
Il est possible que ça soit au niveau de la BDD d'ailleurs, je viens de regarder, les champs sont en utf8_bin. Il faudrait que ça soit du utf8_unicode_ci (du coup faudrait modifier le script SQL)

**Comment by hamadr** [comment]
Possible j'ai fait la modif  avant de m’intéresser à cette issue et du coup le screen plus haut n'a pas d'erreur.

**Comment by hamadr** [comment]
Je referme... Je n'ai plus de bug sur la version de dev
