### ISSUE TITLE
Création de sondage impossible par dessus un événement

### ISSUE THREAD

**Issue by carrieje** [apprentimag/Apprentidate#17]
Contexte:
- Connexion (pour pouvoir ajouter un sondage)
- Création d'un événement
- Ajout d'un sondage

On obtient l'erreur suivante :

```
Vous n'avez pas rempli tous les champs correctement!
```

En plus de ne pas nous aider sur ce qui a mal été rempli, j'ai l'impression que cette phrase apparaît quoi qu'on mette dans les champs.

**Comment by hamadr** [comment]
Le bug est désormais inexistant avec le système d'authentification par mot de passe.
Je ferme jusqu'à qu'on remette en place les comptes persona en parallèle.
