### ISSUE TITLE
Le gravatar ne s'affiche pas

### ISSUE THREAD

**Issue by Flaburgan** [apprentimag/Apprentidate#2]
Ya le petit bonhomme vert à la place à la fois sur mon commentaire et sur la liste des participants.
Comment est-ce que tu as fait pour avoir ton nom et pas ton adresse e-mail, toi qui a ton gravatar qui marche ?

http://apprentimag.fr/apprentidate/zipMug

**Comment by marienfressinaud** [comment]
Tu n'as pas suivi la syntaxe qui est pourtant bien écrite
Ton nom <ton.adresse@mail>

**Comment by Flaburgan** [comment]
Ouais alors là je coinche, deux infos différentes dans le même champ, c'est juste ignoble ça.

Go mettre un champ pseudo au dessus, garçon !

**Comment by marienfressinaud** [comment]
Non, un deuxième champ c'est trop chiant pour l'utilisateur lambda qui veut juste s'ajouter et se barrer. En plus ça serait encore plus moche. Il est pas obligé de mettre son adresse (là j'avoue que je peux essayer de mieux expliciter ça)
En plus c'est la syntaxe de pas mal de trucs (genre git... oui oui mauvais exemple :p)

**Comment by Flaburgan** [comment]
Tu peux bien mettre un deuxième champ sans pour autant le rendre obligatoire. Sinon, et ça me semble beaucoup plus logique, tu bloques l'accès à tout ça si on est pas connecté. Et là, plus besoin de saisir quoi que ce soit :)

**Comment by marienfressinaud** [comment]
Ouais mais j'aime pas l'idée d'avoir deux champs pour simplement des données utilisateur

Et je suis totalement contre l'idée d'être obligé de se connecter pour pouvoir s'inscrire
