### ISSUE TITLE
Impossible d'ajouter un sondage

### ISSUE THREAD

**Issue by marienfressinaud** [apprentimag/Apprentidate#28]
Je suppose qu'il faut être authentifié pour ajouter un sondage, mais en tout cas ça fait bizarre lorsqu'on ne l'est pas et qu'il y a un titre "Sondage" sans rien en-dessous (voir http://apprentimag.fr/apprentidate2/?c=event&a=see&id=OcjHTA)

**Comment by hamadr** [comment]
Je vais rajouter une phrase disant "Aucun sondage n'est disponible pour le moment. Si vous êtes l'administrateur de l’événement vous pouvez en ajouter en vous authentifiant."

**Comment by marienfressinaud** [comment]
Je pense qu'il serait mieux de ne pas afficher le titre tout simplement non ?

**Comment by hamadr** [comment]
Je ne pense pas.
Si on l'enlève ca fait comme si la partie sondages n'existait pas.
 "Aucun sondage n'est disponible pour le moment." ira bien, parce que "Aucun sondage n'est disponible pour le moment. Si vous êtes l'administrateur de l’événement vous pouvez en ajouter en vous authentifiant." ca fait trop de texte selon moi .

**Comment by marienfressinaud** [comment]
D'un côté si aucun sondage n'existe, l'utilisateur en a rien à faire qu'elle existe ou non. Mais comme tu veux :p

**Comment by marienfressinaud** [comment]
Voilà, c'est mis en place :)
