### ISSUE TITLE
XSS dans la colonne des participants

### ISSUE THREAD

**Issue by PaulSec** [apprentimag/Apprentidate#30]
Salut,

Une XSS (Injection de JavaScript) existe dans la colonne des participants;
Certains caractères ne sont pas encodés afin de sécuriser les entrées utilisateurs. 

Afin de tester que tout soit sûr, vous pouvez le premier exemple qui est très complet ici [https://www.owasp.org/index.php/XSS_Filter_Evasion_Cheat_Sheet](https://www.owasp.org/index.php/XSS_Filter_Evasion_Cheat_Sheet)

**Comment by marienfressinaud** [comment]
Pour faire les choses bien il faudrait écrire une fonction `sanitize` qui échappe tous les caractères qui vont bien. Elle doit au moins encapsuler la fonction `htmlspecialchars($param, ENT_COMPAT, 'UTF-8');`

**Comment by PaulSec** [comment]
La fonction `htmlspecialchars()` est suffisante. 

Référence: http://docs.php.net/manual/fr/function.htmlspecialchars.php

**Comment by marienfressinaud** [comment]
Oui je sais, mais il n'y a pas forcément que les balises que je veux nettoyer ;) Et les paramètres supplémentaires, c'est pour s'assurer que c'est bien de l'UTF-8 qui est utilisé (ce n'était pas la valeur par défaut pour PHP 5.3 par exemple… Oui, le PHP c'est crade !)

**Comment by hamadr** [comment]
Cela correspond au ticket #18.
