### ISSUE TITLE
500 ? Hum... 404 !

### ISSUE THREAD

**Issue by Flaburgan** [apprentimag/Apprentidate#4]
Je poste ici même si c'est pas spécifique à apprentidate, sur apprentimag, si on met une mauvaise URL, on se prend systèmatiquement une 500. Vaudrait mieux une 404...

**Comment by marienfressinaud** [comment]
Oui effectivement ce n'est pas du tout spécifique à Apprentidate puisque j'ai bien une erreur 404 quand j'entre une mauvaise url. Pour Apprentimag je regarderai plus tard mais je ferme quand même le bug
