### ISSUE TITLE
Erreur PHP : Call to a member function author() on a non-object[...]

### ISSUE THREAD

**Issue by romainletendart** [apprentimag/Apprentidate#9]
Salut,

Il y a une erreur PHP qui est levée lorsque l'on tente d'accéder à la page suivante :
URL_APPRENTIDATE/?c=event&a=edit

Fatal error: Call to a member function author() on a non-object in /RACINE_APPRENTIDATE/app/controllers/eventController.php on line 104

L'erreur semble survenir lorsqu'il n'y a pas d'id ou que l'id ne correspond pas à un id existant.

**Comment by Flaburgan** [comment]
Tu as obtenu ça en suivant un lien existant ou bien tu as modifié à la main l'url ?

**Comment by romainletendart** [comment]
L'URL a été modifiée à la main.
